import type { NFTItem, NFTCollection, ActivityItem } from "@/features/marketplace/types";

// Base-native generative art — deterministic per token seed, no external CDN dependency
function nftArt(seed: string, style = "shapes") {
  return `https://api.dicebear.com/7.x/${style}/svg?seed=${seed}&backgroundColor=1a1a2e,12121f,0a0a0f&shapeColor=00d4ff,7c3aed,00ff88,ff6b9d`;
}

function colArt(seed: string) {
  return `https://api.dicebear.com/7.x/identicon/svg?seed=${seed}&backgroundColor=0a0a0f,12121f&rowColor=00d4ff,7c3aed,00ff88`;
}

export const MOCK_NFTS: NFTItem[] = [
  {
    id: "1",
    tokenId: "001",
    name: "Neon Genesis #001",
    description: "A genesis piece from the Neon Collection on Base. Rare holographic traits with cosmic background.",
    image: nftArt("neon-genesis-001", "shapes"),
    collection: "Neon Genesis",
    collectionSlug: "neon-genesis",
    price: "0.42",
    priceUsd: 1050,
    owner: "0x1a2b...3c4d",
    creator: "0xartist1",
    category: "art",
    attributes: [
      { trait_type: "Background", value: "Cosmic" },
      { trait_type: "Rarity", value: "Legendary" },
      { trait_type: "Glow", value: "Cyan" },
    ],
    likes: 284,
    isLiked: false,
    listedAt: new Date(Date.now() - 1000 * 60 * 30),
    chain: "base",
    rarity: "Legendary",
  },
  {
    id: "2",
    tokenId: "042",
    name: "Based Punk #042",
    description: "Base-native punk with alien traits. Only 10 with this combination.",
    image: nftArt("based-punk-042", "pixel-art"),
    collection: "Based Punks",
    collectionSlug: "based-punks",
    price: "1.20",
    priceUsd: 3000,
    owner: "0x5e6f...7g8h",
    creator: "0xartist2",
    category: "collectibles",
    attributes: [
      { trait_type: "Type", value: "Alien" },
      { trait_type: "Eyes", value: "Laser" },
      { trait_type: "Background", value: "Deep Purple" },
    ],
    likes: 892,
    isLiked: true,
    listedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    chain: "base",
    rarity: "Epic",
  },
  {
    id: "3",
    tokenId: "0088",
    name: "Pixel Samurai #0088",
    description: "A legendary samurai forged in the digital realm. Gaming NFT with in-world utility.",
    image: nftArt("pixel-samurai-0088", "pixel-art"),
    collection: "Pixel Warriors",
    collectionSlug: "pixel-warriors",
    price: "0.08",
    priceUsd: 200,
    owner: "0x9i0j...1k2l",
    creator: "0xartist3",
    category: "gaming",
    attributes: [
      { trait_type: "Class", value: "Samurai" },
      { trait_type: "Level", value: 88 },
      { trait_type: "Weapon", value: "Katana" },
    ],
    likes: 156,
    isLiked: false,
    listedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
    chain: "base",
    rarity: "Rare",
  },
  {
    id: "4",
    tokenId: "007",
    name: "Sound Wave #007",
    description: "Music NFT with unlockable audio content. Limited 100 edition on Base.",
    image: nftArt("sound-wave-007", "rings"),
    collection: "Sound Waves",
    collectionSlug: "sound-waves",
    price: "0.15",
    priceUsd: 375,
    owner: "0xm3n4...o5p6",
    creator: "0xartist4",
    category: "music",
    attributes: [
      { trait_type: "Genre", value: "Electronic" },
      { trait_type: "Duration", value: "3:42" },
      { trait_type: "Frequency", value: "432Hz" },
    ],
    likes: 67,
    isLiked: false,
    listedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    chain: "base",
    rarity: "Uncommon",
  },
  {
    id: "5",
    tokenId: "333",
    name: "Void Walker #333",
    description: "Born from the void. Rare dark matter energy field with unique aura.",
    image: nftArt("void-walker-333", "shapes"),
    collection: "Void Walkers",
    collectionSlug: "void-walkers",
    price: "0.55",
    priceUsd: 1375,
    owner: "0xq7r8...s9t0",
    creator: "0xartist5",
    category: "art",
    attributes: [
      { trait_type: "Element", value: "Void" },
      { trait_type: "Aura", value: "Dark Matter" },
      { trait_type: "Rarity", value: "Ultra Rare" },
    ],
    likes: 421,
    isLiked: false,
    listedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    chain: "base",
    rarity: "Legendary",
  },
  {
    id: "6",
    tokenId: "1337",
    name: "CyberLens #1337",
    description: "Hyperreal photography captured through augmented optics. 1/1 edition.",
    image: nftArt("cyberlens-1337", "identicon"),
    collection: "CyberLens",
    collectionSlug: "cyberlens",
    price: "0.22",
    priceUsd: 550,
    owner: "0xu1v2...w3x4",
    creator: "0xartist6",
    category: "photography",
    attributes: [
      { trait_type: "Filter", value: "Neural" },
      { trait_type: "Exposure", value: "Golden Hour" },
      { trait_type: "Edition", value: "1/1" },
    ],
    likes: 189,
    isLiked: true,
    listedAt: new Date(Date.now() - 1000 * 60 * 60 * 18),
    chain: "base",
    rarity: "Epic",
  },
];

// Helper to build date labels for the last N days
function buildDates(n: number): string[] {
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return Array.from({ length: n }, (_, i) => {
    const d = new Date(Date.now() - (n - 1 - i) * 24 * 60 * 60 * 1000);
    return `${months[d.getMonth()]} ${d.getDate()}`;
  });
}

const dates30 = buildDates(30);

// Base-native collections with generative cover images
export const MOCK_COLLECTIONS: NFTCollection[] = [
  {
    id: "c1",
    slug: "neon-genesis",
    name: "Neon Genesis",
    description: "The genesis collection of neon-powered digital art on Base. 1,000 unique pieces.",
    image: colArt("neon-genesis-collection"),
    banner: colArt("neon-genesis-banner"),
    floorPrice: "0.38",
    volumeETH: "142.5",
    items: 1000,
    owners: 640,
    verified: true,
    category: "art",
    priceHistory: dates30.map((date, i) => ({
      date,
      floor: parseFloat((0.18 + Math.sin(i * 0.3) * 0.05 + i * 0.007 + Math.random() * 0.02).toFixed(3)),
      volume: parseFloat((8 + Math.sin(i * 0.5) * 3 + Math.random() * 4).toFixed(1)),
    })),
  },
  {
    id: "c2",
    slug: "void-walkers",
    name: "Void Walkers",
    description: "2,222 walkers from beyond the digital veil. Each uniquely generated on Base.",
    image: colArt("void-walkers-collection"),
    banner: colArt("void-walkers-banner"),
    floorPrice: "0.50",
    volumeETH: "89.2",
    items: 2222,
    owners: 1200,
    verified: true,
    category: "art",
    priceHistory: dates30.map((date, i) => ({
      date,
      floor: parseFloat((0.60 - Math.cos(i * 0.25) * 0.08 - i * 0.003 + Math.random() * 0.025).toFixed(3)),
      volume: parseFloat((5 + Math.cos(i * 0.4) * 2 + Math.random() * 3).toFixed(1)),
    })),
  },
  {
    id: "c3",
    slug: "pixel-warriors",
    name: "Pixel Warriors",
    description: "10,000 warriors ready for the on-chain battle. Gaming NFTs on Base.",
    image: colArt("pixel-warriors-collection"),
    banner: colArt("pixel-warriors-banner"),
    floorPrice: "0.07",
    volumeETH: "456.8",
    items: 10000,
    owners: 5400,
    verified: false,
    category: "gaming",
    priceHistory: dates30.map((date, i) => ({
      date,
      floor: parseFloat((0.04 + Math.abs(Math.sin(i * 0.6)) * 0.025 + i * 0.001 + Math.random() * 0.008).toFixed(4)),
      volume: parseFloat((22 + Math.sin(i * 0.3) * 8 + Math.random() * 10).toFixed(1)),
    })),
  },
  {
    id: "c4",
    slug: "based-punks",
    name: "Based Punks",
    description: "The iconic punk aesthetic, native to Base. 10,000 unique punks on-chain.",
    image: colArt("based-punks-collection"),
    banner: colArt("based-punks-banner"),
    floorPrice: "1.10",
    volumeETH: "2300.1",
    items: 10000,
    owners: 3200,
    verified: true,
    category: "collectibles",
    priceHistory: dates30.map((date, i) => ({
      date,
      floor: parseFloat((0.75 + Math.sin(i * 0.2) * 0.12 + i * 0.015 + Math.random() * 0.05).toFixed(3)),
      volume: parseFloat((95 + Math.sin(i * 0.35) * 30 + Math.random() * 20).toFixed(1)),
    })),
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "a-offer-1",
    type: "offer",
    nftName: "Neon Genesis #001",
    nftImage: nftArt("neon-genesis-001", "shapes"),
    collection: "Neon Genesis",
    price: "0.36",
    from: "0xdead...beef",
    to: "0xYOU",
    timestamp: new Date(Date.now() - 1000 * 60 * 8),
    offerExpiryDays: 3,
  },
  {
    id: "a-offer-2",
    type: "offer",
    nftName: "CyberLens #1337",
    nftImage: nftArt("cyberlens-1337", "identicon"),
    collection: "CyberLens",
    price: "0.19",
    from: "0xab12...cd34",
    to: "0xYOU",
    timestamp: new Date(Date.now() - 1000 * 60 * 22),
    offerExpiryDays: 6,
  },
  {
    id: "a1",
    type: "sale",
    nftName: "Neon Genesis #001",
    nftImage: nftArt("neon-genesis-001", "shapes"),
    collection: "Neon Genesis",
    price: "0.42",
    from: "0x1a2b...3c4d",
    to: "0x5e6f...7g8h",
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: "a-accepted-1",
    type: "accepted",
    nftName: "Void Walker #333",
    nftImage: nftArt("void-walker-333", "shapes"),
    collection: "Void Walkers",
    price: "0.50",
    from: "0xf1e2...d3c4",
    to: "0xq7r8...s9t0",
    timestamp: new Date(Date.now() - 1000 * 60 * 28),
  },
  {
    id: "a2",
    type: "listing",
    nftName: "Void Walker #333",
    nftImage: nftArt("void-walker-333", "shapes"),
    collection: "Void Walkers",
    price: "0.55",
    from: "0xq7r8...s9t0",
    to: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: "a3",
    type: "offer",
    nftName: "Based Punk #042",
    nftImage: nftArt("based-punk-042", "pixel-art"),
    collection: "Based Punks",
    price: "1.05",
    from: "0x9i0j...1k2l",
    to: "",
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    offerExpiryDays: 5,
  },
  {
    id: "a4",
    type: "sale",
    nftName: "Pixel Samurai #0088",
    nftImage: nftArt("pixel-samurai-0088", "pixel-art"),
    collection: "Pixel Warriors",
    price: "0.08",
    from: "0xm3n4...o5p6",
    to: "0x9i0j...1k2l",
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
  },
  {
    id: "a5",
    type: "transfer",
    nftName: "Sound Wave #007",
    nftImage: nftArt("sound-wave-007", "rings"),
    collection: "Sound Waves",
    price: "0.00",
    from: "0xu1v2...w3x4",
    to: "0x1a2b...3c4d",
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
  },
];
